name: Sync Deploy Folder to S3

on:  # Trigger when files in the deploy folder are pushed or deleted
  push: 
    branches:
      - main
    paths:
      - 'deploy/**'
  delete:
    paths:
      - 'deploy/**'

# Allow manual trigger
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install AWS CLI
      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      # Sync changes to S3
      - name: Sync Deploy Folder with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync deploy s3://$S3_BUCKET/deploy --delete
      # Debug Sync Output
      - name: Debug Sync Output
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 ls s3://$S3_BUCKET/deploy --recursive